# Generated by Django 3.2.7 on 2025-01-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notesapp', '0002_auto_20210905_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='notesapp.text')),
            ],
        ),
    ]
