# Generated by Django 5.2.4 on 2025-08-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_created_at_tag_reminder_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='reminder_datetime',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='reminder_notified',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
    ]
