# Generated by Django 5.2.4 on 2025-08-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_tag_created_at_remove_tag_reminder_datetime_and_more'),
        ('notesapp', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednotepermission',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_permissions', to='notesapp.note'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='notesapp.note'),
        ),
    ]
