# Generated by Django 5.2.4 on 2025-08-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_auto_20210905_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='reminder_notified',
            field=models.BooleanField(default=False),
        ),
    ]
