# Generated by Django 5.2.4 on 2025-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_text_reminder_at_text_reminder_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('Uname', models.CharField(max_length=30)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_notified', models.BooleanField(default=False)),
            ],
        ),
    ]
