# Generated by Django 5.2.4 on 2025-08-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_sharednotepermission_note_alter_tag_note'),
        ('notesapp', '0004_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text',
        ),
    ]
